### ISSUE TITLE
Debian Deb822 format Support

### ISSUE THREAD

**Issue by mudongliang** [hust-open-atom-club/hustmirror-cli#9]
Debian docker now by default uses /etc/apt/sources.list.d/debian.sources with Deb822 format to store system software sources.

The temporary solution is to delete this file and regenerate sources.list in the /etc/apt/.

This format may be the future of Debian. We need a final solution for this format - directly modify the new source list.

[1]https://manpages.debian.org/bookworm/dpkg-dev/deb822.5.en.html

**Comment by jxlpzqc** [comment]
Fixed in #25
